sboter4u:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    base_joint:
        type: effort_controllers/JointPositionController
        joint: base_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    shoulder_joint:
        type: effort_controllers/JointPositionController
        joint: soulder_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    elbow_joint:
        type: effort_controllers/JointPositionController
        joint: elbow_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    pitch_joint:
        type: effort_controllers/JointPositionController
        joint: pitch_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    roll_joint:
        type: effort_controllers/JointPositionController
        joint: roll_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    pad1_joint:
        type: effort_controllers/JointPositionController
        joint: pad1_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    pad2_joint:
        type: effort_controllers/JointPositionController
        joint: pad2_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

