// Generated by gencpp from file andreas_arm_drivers/motor_driverResponse.msg
// DO NOT EDIT!


#ifndef ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERRESPONSE_H
#define ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace andreas_arm_drivers
{
template <class ContainerAllocator>
struct motor_driverResponse_
{
  typedef motor_driverResponse_<ContainerAllocator> Type;

  motor_driverResponse_()
    : pass(false)  {
    }
  motor_driverResponse_(const ContainerAllocator& _alloc)
    : pass(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pass_type;
  _pass_type pass;




  typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motor_driverResponse_

typedef ::andreas_arm_drivers::motor_driverResponse_<std::allocator<void> > motor_driverResponse;

typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverResponse > motor_driverResponsePtr;
typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverResponse const> motor_driverResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace andreas_arm_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'andreas_arm_drivers': ['/home/criag/andreas_arm/src/andreas_arm_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31ba47e3b9082e938070390a82f04cc7";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31ba47e3b9082e93ULL;
  static const uint64_t static_value2 = 0x8070390a82f04cc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "andreas_arm_drivers/motor_driverResponse";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool pass\n\
\n\
";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pass);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_driverResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::andreas_arm_drivers::motor_driverResponse_<ContainerAllocator>& v)
  {
    s << indent << "pass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pass);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERRESPONSE_H
