// Generated by gencpp from file andreas_arm_drivers/motor_driverRequest.msg
// DO NOT EDIT!


#ifndef ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERREQUEST_H
#define ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace andreas_arm_drivers
{
template <class ContainerAllocator>
struct motor_driverRequest_
{
  typedef motor_driverRequest_<ContainerAllocator> Type;

  motor_driverRequest_()
    : angle(0.0)
    , time(0)  {
    }
  motor_driverRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , time(0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef uint64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_driverRequest_

typedef ::andreas_arm_drivers::motor_driverRequest_<std::allocator<void> > motor_driverRequest;

typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverRequest > motor_driverRequestPtr;
typedef boost::shared_ptr< ::andreas_arm_drivers::motor_driverRequest const> motor_driverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace andreas_arm_drivers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'andreas_arm_drivers': ['/home/criag/andreas_arm/src/andreas_arm_drivers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a7410b1b7d661859b5859ebf61af241";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a7410b1b7d66185ULL;
  static const uint64_t static_value2 = 0x9b5859ebf61af241ULL;
};

template<class ContainerAllocator>
struct DataType< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "andreas_arm_drivers/motor_driverRequest";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle\n\
uint64 time\n\
";
  }

  static const char* value(const ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct motor_driverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::andreas_arm_drivers::motor_driverRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANDREAS_ARM_DRIVERS_MESSAGE_MOTOR_DRIVERREQUEST_H
